/*
  ____                                   _             _       
 / ___|  ___  _   _ _ __ ___ ___   _ __ | |_   _  __ _(_)_ __  
 \___ \ / _ \| | | | '__/ __/ _ \ | '_ \| | | | |/ _` | | '_ \ 
  ___) | (_) | |_| | | | (_|  __/ | |_) | | |_| | (_| | | | | |
 |____/ \___/ \__,_|_|  \___\___| | .__/|_|\__,_|\__, |_|_| |_|
                                  |_|            |___/         
# A Template for Hello_sourcePlugin, a Source Plugin
# Generated by the command: plugin hello_source --type source
# Hostname: insa-09082
# Current working directory: /home-local/fcardenas-ac/plugin_tut
# Creation date: 2026-07-29T17:13:14.334+0200
# NOTICE: MADS Version 2.3.0
*/
// Mandatory included headers
#include <source.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>

// other includes as needed here

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "hello_source"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class Hello_sourcePlugin : public Source<json> {

public:
  // Don't forget to inherit the constructors of the parent class
  // If you really need to implement your own constructor, make sure to call 
  // the parent constructor. Normally, use set_params() to set the parameters
  // instead of the constructor.
  using Source::Source; // inherit constructors

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: the result is published
  // return_type::retry: go to next loop, nothing is published
  // return_type::warning: content of _error is added to result befor publishing
  // return_type::error: the result only has a copy of _error
  // return_type::critical: execution stops
  return_type get_output(json &out, vector<unsigned char> *blob = nullptr) override {
    out.clear();

    // load the data as necessary and set the fields of the json out variable
    out["message"] = _params.value("message","Hello from my first MADS plugin");
    out["counter"] = _counter;
    _counter++;
    // This sets the agent_id field in the output json object, only when it is
    // not empty
    if (!_agent_id.empty()) out["agent_id"] = _agent_id;
    return return_type::success;
  }

  void set_params(const json &params) override {
    // Call the parent class method to set the common parameters 
    // (e.g. agent_id, etc.)
    Source::set_params(params);

    // provide sensible defaults for the parameters by setting e.g.
    _params["message"] = "Hello from my first MADS plugin";
    // more here...

    // then merge the defaults with the actually provided parameters
    // params needs to be cast to json
    _params.merge_patch(params);
    
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    // return a map of strings with additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent
    
    return {
      {"description", "simple source plugin to learn MADS"},
      {"version", "1.0"}
    };
    
  };

private:
  // Define the fields that are used to store internal resources
  int _counter = 0;
};


/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
INSTALL_SOURCE_DRIVER(Hello_sourcePlugin, json)


/*
                  _
  _ __ ___   __ _(_)_ __
 | '_ ` _ \ / _` | | '_ \
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|

For testing purposes, when directly executing the plugin
*/
int main(int argc, char const *argv[]) {
  Hello_sourcePlugin plugin;
  json output, params;

  // Set example values to params
  params["message"] = "Hello from the standalone test";

  // Set the parameters
  plugin.set_params(params);

  for(int i = 0; i < 5; i++){
    // Process data
    plugin.get_output(output);
    // Produce output
    cout << "Output: " << output << endl;
  };


  return 0;
}
